#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service defaults *-nginx
prepare_service single
SERVICE_NAME="php-fpm"

check_container_initialized
check_service_initialized init
liftoff

print_start "Starting php-fpm ${PHP_VERSION}"
exec s6-setuidgid "${PHPFPM_USER}" env HOME="$(getent passwd "${PHPFPM_USER}" | cut -d: -f6)" php-fpm -F
